# Generated by Django 4.2.3 on 2023-07-22 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product_itemsimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='itemsimg',
            field=models.ImageField(null=True, upload_to='products'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
            ],
        ),
    ]
