# Generated by Django 4.2.3 on 2023-08-01 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_cart_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='itemsimg',
            new_name='items_img',
        ),
    ]
