# Generated by Django 4.2.3 on 2023-08-02 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_author_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='name',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
